import {TANKS,MISSIONS,UPGRADES} from './data.js';
import {Battle} from './battle.js';
import {AudioDirector} from './audio.js';
import {EffectDirector} from './vfx.js';
import {SAVE_KEY,SETTINGS_KEY,createProfile,sanitizeProfile,isUnlocked,completeMission,purchaseUpgrade,safeRead,safeWrite} from './storage.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let profile=createProfile();let damagedSave=false;
try{const s=safeRead(SAVE_KEY);if(s)profile=sanitizeProfile(JSON.parse(s),MISSIONS.map(m=>m.id),TANKS.map(t=>t.id))}catch{damagedSave=true}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let settings={master:.8,music:.52,sfx:.8,muted:false,low:reduced||matchMedia('(max-width: 800px)').matches};
try{const stored=JSON.parse(safeRead(SETTINGS_KEY)||'null');if(stored){for(const k of ['master','music','sfx'])if(Number.isFinite(stored[k]))settings[k]=Math.max(0,Math.min(1,stored[k]));for(const k of ['muted','low'])if(typeof stored[k]==='boolean')settings[k]=stored[k]}}catch{}
const audio=new AudioDirector(settings);audio.setMuted(settings.muted);audio.setScene('menu');
let selected=MISSIONS.findIndex((m,i)=>isUnlocked(profile,MISSIONS,i)&&!profile.missions[m.id]);if(selected<0)selected=0;
let battle=null,vfx=null,currentMission=null,training=false,lastResult=null,state=null,currentPage='campaign',paused=false,toastTimer,charge=null,vfxFrame=0,angleFrame=0;
const atlas=new Image();atlas.src='assets/art/tanks.png';const crops={bastion:[10,184,533,344],striker:[553,187,543,347],arc:[1100,201,526,316],warden:[1646,176,519,352]};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4000)}
function save(){if(!safeWrite(SAVE_KEY,profile))toast('저장 공간을 사용할 수 없습니다. 설정에서 진행 기록을 내보내세요.')}
function drawTank(canvas,id){if(!canvas)return;canvas.width=460;canvas.height=220;const c=canvas.getContext('2d');c.clearRect(0,0,460,220);const rect=crops[id];if(atlas.complete&&atlas.naturalWidth){const scale=Math.min(420/rect[2],200/rect[3]);c.drawImage(atlas,...rect,(460-rect[2]*scale)/2,(220-rect[3]*scale)/2,rect[2]*scale,rect[3]*scale)}else{c.fillStyle=TANKS.find(t=>t.id===id)?.color||'#7be0ce';c.fillRect(75,100,270,70);c.fillRect(155,65,130,70);c.fillRect(240,75,150,12)}}
atlas.onload=()=>$$('canvas[data-tank]').forEach(c=>drawTank(c,c.dataset.tank));
function refreshCredits(){$('#credits').textContent=profile.credits.toLocaleString('ko-KR')}
function stars(n){return '★'.repeat(n)+'☆'.repeat(3-n)}
function renderCampaign(){refreshCredits();$('#campaign-progress').textContent=`${Object.keys(profile.missions).length} / ${MISSIONS.length}`;$('#total-stars').textContent=`★ ${Object.values(profile.missions).reduce((a,b)=>a+b,0)} / 27`;$('#continue-button').innerHTML=`${Object.keys(profile.missions).length?'작전 계속하기':'작전 시작'} <span>↗</span>`;
 const regions=[...new Set(MISSIONS.map(m=>m.region))];$('#missions').innerHTML=regions.map((region,ri)=>`<section class="mission-region"><div class="region-title">0${ri+1} / ${region}<small>${['COASTLINE','ASH DESERT','FROZEN RELAY'][ri]}</small></div><div class="mission-row">${MISSIONS.map((m,i)=>({m,i})).filter(({m})=>m.region===region).map(({m,i})=>`<button class="mission-card ${i===selected?'selected':''} ${isUnlocked(profile,MISSIONS,i)?'':'locked'}" data-mission="${i}" ${isUnlocked(profile,MISSIONS,i)?'':'disabled'} aria-label="작전 ${i+1} ${m.name}${isUnlocked(profile,MISSIONS,i)?'':' 잠김'}" aria-pressed="${i===selected}"><span class="mission-number">OP. ${String(i+1).padStart(2,'0')}</span><strong>${m.name}</strong><span class="stars">${stars(profile.missions[m.id]||0)}</span>${isUnlocked(profile,MISSIONS,i)?'':'<span class="lock">잠김</span>'}</button>`).join('')}</div></section>`).join('');$$('[data-mission]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.mission);audio.event('ui');renderCampaign()});renderBriefing();}
function renderBriefing(){const m=MISSIONS[selected],tank=TANKS.find(t=>t.id===profile.tank)||TANKS[0];$('#briefing').innerHTML=`<div class="eyebrow">BRIEFING / ${String(selected+1).padStart(2,'0')}</div><h3>${m.name}</h3><p>${m.briefing}</p><div class="briefing-objective"><span>MISSION OBJECTIVE</span><p>${m.objective}</p></div><div class="briefing-details"><span>초회 작전 보상</span><b>◆ ${m.reward} CR</b></div><div class="briefing-details"><span>별 등급</span><span>생존율 · 전투 라운드</span></div><div class="selected-tank"><canvas data-tank="${tank.id}" aria-hidden="true"></canvas><div><small>DEPLOYMENT</small><strong>${tank.name}</strong></div><button id="change-tank">변경 ↗</button></div><button class="primary" id="deploy-button">전투 진입 <span>→</span></button>`;drawTank($('#briefing canvas'),tank.id);$('#change-tank').onclick=()=>setPage('hangar');$('#deploy-button').onclick=()=>startBattle(m,false);}
function renderHangar(){refreshCredits();$('#tank-grid').innerHTML=TANKS.map(t=>`<button class="tank-card ${profile.tank===t.id?'selected':''}" data-select-tank="${t.id}" aria-pressed="${profile.tank===t.id}"><div class="tank-role">${t.role}</div><canvas data-tank="${t.id}" aria-hidden="true"></canvas><h3>${t.name}</h3><p>${t.description}</p><div class="tank-stats">${[['내구력',t.hp,420],['화력',t.attack,1.35],['기동력',t.mobility,1.5]].map(([label,v,max])=>`<div class="tank-stat"><span>${label}</span><span><i style="--value:${Math.min(100,v/max*100)}%"></i></span></div>`).join('')}</div></button>`).join('');$$('[data-select-tank]').forEach(b=>b.onclick=()=>{profile.tank=b.dataset.selectTank;save();audio.event('ui');renderHangar();toast(`${TANKS.find(t=>t.id===profile.tank).name} 배치 준비 완료`)});$$('#tank-grid canvas').forEach(c=>drawTank(c,c.dataset.tank));$('#upgrade-grid').innerHTML=Object.entries(UPGRADES).map(([id,u])=>{const level=profile.upgrades[id]||0,cost=u.costs[level],max=level>=u.max;return `<article class="upgrade-card"><span class="eyebrow">LEVEL ${level} / ${u.max}</span><h3>${u.label}</h3><p>${u.description}</p><div class="levels">${Array.from({length:u.max},(_,i)=>`<i class="${i<level?'on':''}"></i>`).join('')}</div><button class="secondary" data-upgrade="${id}" ${max||profile.credits<cost?'disabled':''}><span>${max?'최고 단계':profile.credits<cost?'크레딧 부족':'강화하기'}</span><b>${max?'MAX':`◆ ${cost} CR`}</b></button></article>`}).join('');$$('[data-upgrade]').forEach(b=>b.onclick=()=>{const id=b.dataset.upgrade;if(purchaseUpgrade(profile,id,UPGRADES[id])){save();audio.event('repair');renderHangar();toast(`${UPGRADES[id].label} 강화 완료`)}})}
function setPage(page){if(battle)return;currentPage=page;$$('.menu-page').forEach(el=>el.hidden=el.id!==`${page}-page`);$('.hero').hidden=page!=='campaign';$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='hangar')renderHangar();else if(page==='campaign')renderCampaign();audio.event('ui');}
$$('[data-page]').forEach(b=>b.onclick=()=>{if(battle)goHome();setPage(b.dataset.page)});$('#continue-button').onclick=()=>{const i=MISSIONS.findIndex((m,i)=>isUnlocked(profile,MISSIONS,i)&&!profile.missions[m.id]);selected=i<0?selected:i;renderCampaign();startBattle(MISSIONS[selected],false)};$('#training-start').onclick=()=>startBattle(MISSIONS[0],true);
function resizeVfx(){if(!vfx||!battle)return;const c=$('#vfx-canvas');const r=c.getBoundingClientRect();vfx.resize(r.width,r.height,Math.min(devicePixelRatio||1,2))}
function runVfx(){if(!vfx)return;let before=performance.now();function step(now){if(!vfx)return;const dt=Math.min(.05,(now-before)/1000);before=now;if(!paused&&!document.hidden){vfx.update(dt);vfx.render()}vfxFrame=requestAnimationFrame(step)}vfxFrame=requestAnimationFrame(step)}
function handleEvent(type,data={}){audio.event(type,{power:data.intensity??1,pan:Math.max(-1,Math.min(1,((data.x??720)-720)/720))});if(vfx&&['fire','impact','shield','repair'].includes(type)){const rect=$('#vfx-canvas').getBoundingClientRect();const scale=battle.scale;vfx.emit(type==='repair'?'heal':type,battle.offsetX+(data.x??720)*scale,battle.offsetY+(data.y??400)*scale,{...data,intensity:data.intensity??1})}}
function startBattle(m,isTraining=false){audio.unlock();closeDialogs();stopBattle();currentMission=m;training=isTraining;lastResult=null;state=null;paused=false;document.body.classList.add('in-battle');$('#view-toggle').textContent='전체 전장';$('#view-toggle').setAttribute('aria-pressed','false');$('#menu-view').hidden=true;$('#battle-view').hidden=false;$$('.nav-button').forEach(b=>b.classList.remove('active'));$('#battle-title').textContent=m.name;$('#battle-region').textContent=`${isTraining?'TRAINING':'OPERATION'} ${String(MISSIONS.indexOf(m)+1).padStart(2,'0')} / ${m.region}`;$('#battle-objective').textContent=m.objective;audio.resume();audio.setScene('battle');audio.setIntensity(.15);const t=TANKS.find(t=>t.id===profile.tank)||TANKS[0];try{vfx=new EffectDirector($('#vfx-canvas'));vfx.setQuality(settings.low?'low':'high')}catch{vfx=null}battle=new Battle($('#battle-canvas'),{mission:m,tank:t,upgrades:profile.upgrades,onState:updateState,onEvent:handleEvent,onFinish:finishBattle});battle.reducedMotion=settings.low;resizeVfx();runVfx();window.scrollTo(0,0);}
function stopBattle(){document.body.classList.remove('in-battle');cancelCharge();stopInputs();cancelAnimationFrame(vfxFrame);vfxFrame=0;vfx?.destroy();vfx=null;battle?.destroy();battle=null;state=null;}
function updateState(next){state=next;const own=next.phase==='aim'&&!paused;$('#hp-text').textContent=`${Math.ceil(next.playerHp)} / ${next.playerMaxHp}`;$('#hp-bar').style.width=`${Math.max(0,next.playerHp/next.playerMaxHp*100)}%`;$('#hp-bar').style.background=next.playerHp/next.playerMaxHp<.3?'var(--danger)':'var(--teal)';$('#wind-text').textContent=`${next.wind<0?'←':'→'} ${Math.abs(next.wind).toFixed(1)}`;$('#round-label').textContent=`ROUND ${String(next.round).padStart(2,'0')}`;$('#angle-output').textContent=`${Math.round(next.angle)}°`;$('#power-output').textContent=`${Math.round(next.power)}%`;if(document.activeElement!==$('#angle'))$('#angle').value=next.angle;if(!charge&&document.activeElement!==$('#power'))$('#power').value=next.power;$('#fuel-text').textContent=`${Math.ceil(next.fuel)} / ${next.fuelMax}`;$('#turn-banner').textContent=next.status||next.text||(own?'YOUR TURN · 포격 준비':next.phase==='projectile'?'SHOT IN FLIGHT':'ENEMY TURN · 적 포격');$('#battle-hint').textContent=own?'각도와 화력을 조절한 뒤 발사하세요. 보호막·수리는 전투당 한 번.':next.phase==='ended'?'작전 결과를 정리하고 있습니다.':'적의 궤적을 관찰하고 다음 턴을 준비하세요.';$('#enemy-health').innerHTML=next.enemies.map((e,i)=>`<span class="enemy-line"><span>${e.hp>0?`HOSTILE ${String(i+1).padStart(2,'0')}`:'DESTROYED'}</span><b>${Math.max(0,Math.ceil(e.hp))}</b></span>`).join('');$$('.move-button,#angle,#power,#fire-button').forEach(b=>b.disabled=!own);$$('[data-weapon]').forEach(b=>{const id=b.dataset.weapon;b.classList.toggle('selected',next.weapon===id);const ammo=next.ammo[id];b.querySelector('small').textContent=Number.isFinite(ammo)?ammo:'∞';b.disabled=!own||ammo===0});$$('[data-ability]').forEach(b=>{const n=next.abilities[b.dataset.ability];b.querySelector('small').textContent=n??0;b.disabled=!own||!n});audio.setIntensity(next.intensity??Math.max(.15,1-next.playerHp/next.playerMaxHp));if(!own)cancelCharge();}
function finishBattle(result){cancelCharge();lastResult=result;audio.setIntensity(0);const reward=training?0:completeMission(profile,currentMission,result);if(!training)save();refreshCredits();$('#result-eyebrow').textContent=training?'TRAINING COMPLETE':result.won?'MISSION ACCOMPLISHED':'SIGNAL LOST';$('#result-mark').textContent=result.won?'✦':'◇';$('#result-mark').style.color=result.won?'var(--teal)':'var(--danger)';$('#result-title').textContent=result.won?'전선 확보':'다시, 다음 한 발';$('#result-description').textContent=result.won?training?'훈련을 마쳤습니다. 작전 지도에서 캠페인을 시작하세요.':`${currentMission.name} 작전 완료. ${reward?`◆ ${reward} CR을 획득했습니다.`:'최고 기록이 저장되어 있습니다.'}`:'위치와 탄종을 바꿔 다시 도전하세요. 획득한 강화는 유지됩니다.';$('#result-stars').textContent=result.won?stars(result.stars):'☆☆☆';$('#result-stats').innerHTML=`<span><b>${result.rounds}</b>라운드</span><span><b>${Math.max(0,Math.round(result.hpRemaining))}</b>남은 내구력</span><span><b>${reward}</b>획득 CR</span>`;const i=MISSIONS.indexOf(currentMission);$('#result-next').hidden=!result.won||training||i===MISSIONS.length-1;$('#result-next').textContent='다음 작전 →';setTimeout(()=>{if(battle&&lastResult===result)$('#result-dialog').showModal()},800);}
function goHome(){closeDialogs();stopBattle();paused=false;audio.resume();audio.setScene('menu');audio.setIntensity(0);$('#battle-view').hidden=true;$('#menu-view').hidden=false;setPage('campaign');window.scrollTo(0,0)}
$('#result-home').onclick=goHome;$('#exit-button').onclick=goHome;$('#result-retry').onclick=()=>startBattle(currentMission,training);$('#restart-button').onclick=()=>startBattle(currentMission,training);$('#result-next').onclick=()=>{selected=Math.min(MISSIONS.length-1,MISSIONS.indexOf(currentMission)+1);startBattle(MISSIONS[selected],false)};
function closeDialogs(){$$('dialog[open]').forEach(d=>d.close())}
function setPaused(value){if(!battle||state?.phase==='ended')return;paused=value;battle.pause(value);cancelCharge();stopInputs();if(value){audio.pause();$('#pause-dialog').showModal()}else{audio.resume();$('#pause-dialog').close()}if(state)updateState(state)}
$('#pause-button').onclick=()=>setPaused(true);$('#resume-button').onclick=()=>setPaused(false);$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();setPaused(false)});$('#result-dialog').addEventListener('cancel',e=>{e.preventDefault();goHome()});
$('#angle').oninput=e=>battle?.setAngle(+e.target.value);$('#power').oninput=e=>battle?.setPower(+e.target.value);$$('[data-weapon]').forEach(b=>b.onclick=()=>{battle?.setWeapon(b.dataset.weapon);audio.event('ui')});$$('[data-ability]').forEach(b=>b.onclick=()=>battle?.useAbility(b.dataset.ability));
function beginCharge(){if(!battle||paused||state?.phase!=='aim'||charge)return;audio.unlock();const start=performance.now(),base=state.power;charge={start,base,frame:0};const tick=now=>{if(!charge)return;const elapsed=(now-start)/1000;if(elapsed>.18){const span=(elapsed-.18)*38;const wave=span%180;const power=10+(wave<=90?wave:180-wave);battle.setPower(power);$('#power').value=power;$('#charge-progress').style.width=`${power}%`}charge.frame=requestAnimationFrame(tick)};charge.frame=requestAnimationFrame(tick);}
function cancelCharge(){if(charge)cancelAnimationFrame(charge.frame);charge=null;$('#charge-progress').style.width='0%'}
function endCharge(){if(!charge)return;cancelCharge();if(battle&&!paused&&state?.phase==='aim')battle.fire()}
$('#fire-button').addEventListener('keydown',e=>{if(e.code==='Enter'){e.preventDefault();audio.unlock();battle?.fire()}});
$('#fire-button').addEventListener('pointerdown',e=>{e.preventDefault();if(e.button!==0)return;$('#fire-button').setPointerCapture(e.pointerId);beginCharge()});$('#fire-button').addEventListener('pointerup',e=>{e.preventDefault();endCharge()});$('#fire-button').addEventListener('pointercancel',cancelCharge);$('#fire-button').addEventListener('lostpointercapture',cancelCharge);
for(const [selector,direction] of [['#move-left',-1],['#move-right',1]]){const b=$(selector);b.addEventListener('pointerdown',e=>{if(b.disabled)return;e.preventDefault();b.setPointerCapture(e.pointerId);battle?.setMove(direction)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>battle?.setMove(0))}
const keys=new Set();function stopInputs(){keys.clear();battle?.setMove(0);cancelAnimationFrame(angleFrame);angleFrame=0;}
function angleTick(){if(!battle||!keys.size||paused){angleFrame=0;return}if(state?.phase==='aim'){const delta=(keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0);if(delta)battle.setAngle(state.angle+delta)}angleFrame=requestAnimationFrame(angleTick)}
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||e.target.isContentEditable)return;if(e.code==='Escape'&&battle){e.preventDefault();if(!$$('dialog[open]').length)setPaused(true);return}if(!battle||paused||$$('dialog[open]').length)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','Digit1','Digit2','Digit3'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.code==='ArrowLeft'||e.code==='ArrowRight')battle.setMove((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0));if((e.code==='ArrowUp'||e.code==='ArrowDown')&&!angleFrame)angleFrame=requestAnimationFrame(angleTick);if(e.code==='Space'&&!e.repeat)beginCharge();if(/^Digit[123]$/.test(e.code))battle.setWeapon(['shell','cluster','arc'][Number(e.code.slice(-1))-1])});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='ArrowLeft'||e.code==='ArrowRight')battle?.setMove((keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0));if(e.code==='Space')endCharge()});
window.addEventListener('blur',()=>{cancelCharge();stopInputs();if(battle&&!paused&&state?.phase!=='ended')setPaused(true)});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelCharge();stopInputs();audio.pause();if(battle&&!paused&&state?.phase!=='ended')setPaused(true)}else if(!paused)audio.resume()});window.addEventListener('resize',()=>{battle?.resize();resizeVfx()});document.addEventListener('fullscreenchange',()=>{battle?.resize();resizeVfx()});document.addEventListener('pointerdown',()=>audio.unlock(),{passive:true});
function applySettings(){audio.setVolumes(settings);audio.setMuted(settings.muted);vfx?.setQuality(settings.low?'low':'high');if(battle)battle.reducedMotion=settings.low;for(const channel of ['master','music','sfx']){$(`#${channel}-volume`).value=settings[channel];$(`#${channel}-output`).textContent=`${Math.round(settings[channel]*100)}%`}$('#mute-toggle').checked=settings.muted;$('#quality-toggle').checked=settings.low;safeWrite(SETTINGS_KEY,settings)}
for(const channel of ['master','music','sfx'])$(`#${channel}-volume`).oninput=e=>{settings[channel]=Number(e.target.value);applySettings()};$('#mute-toggle').onchange=e=>{settings.muted=e.target.checked;applySettings()};$('#quality-toggle').onchange=e=>{settings.low=e.target.checked;applySettings()};$('#settings-button').onclick=()=>{if(battle&&!paused&&state?.phase!=='ended')setPaused(true);$('#settings-dialog').showModal()};$$('[data-close]').forEach(b=>b.onclick=()=>$(`#${b.dataset.close}`).close());$('#fullscreen-button').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('이 브라우저에서는 전체화면을 사용할 수 없습니다.')}};
$('#save-export').onclick=()=>{const blob=new Blob([JSON.stringify(profile,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`fortress-save-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('진행 기록을 내보냈습니다.')};$('#save-import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw new Error('파일이 너무 큽니다.');const imported=sanitizeProfile(JSON.parse(await file.text()),MISSIONS.map(m=>m.id),TANKS.map(t=>t.id));profile=imported;save();refreshCredits();renderCampaign();if(currentPage==='hangar')renderHangar();toast('진행 기록을 가져왔습니다.')}catch(err){toast(err.message||'진행 기록을 읽을 수 없습니다.')}e.target.value=''};
applySettings();renderCampaign();if(damagedSave)toast('진행 기록을 읽지 못했습니다. 원래 기록은 보존하고 새 세션을 시작합니다.');
window.FortressAfterlight={get state(){return state?JSON.parse(JSON.stringify(state)):null},get profile(){return JSON.parse(JSON.stringify(profile))},get audio(){return audio},get battle(){return battle},get effects(){return vfx},version:'2.0.0'};

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{}));}

$('#view-toggle').onclick=()=>{if(!battle)return;battle.overview=!battle.overview;battle.resize();resizeVfx();$('#view-toggle').textContent=battle.overview?'전차 확대':'전체 전장';$('#view-toggle').setAttribute('aria-pressed',String(battle.overview));};
