import {TANKS,UPGRADES} from './data.js';
import {drawModifications} from './appearance.js';
const $=s=>document.querySelector(s),atlas=new Image(),levels=Object.fromEntries(Object.keys(UPGRADES).map(id=>[id,0]));
const crops={bastion:[10,184,533,344],striker:[553,187,543,347],arc:[1100,201,526,316],warden:[1646,176,519,352]};
function card(t,label,parts){const f=document.createElement('figure'),c=document.createElement('canvas');c.width=460;c.height=220;c.setAttribute('role','img');c.setAttribute('aria-label',`${t.name} ${label}`);const ctx=c.getContext('2d'),r=crops[t.id],scale=Math.min(420/r[2],200/r[3]);ctx.drawImage(atlas,...r,(460-r[2]*scale)/2,(220-r[3]*scale)/2,r[2]*scale,r[3]*scale);ctx.save();ctx.translate(230,160);ctx.scale(3.2,3.2);drawModifications(ctx,parts);ctx.restore();const caption=document.createElement('figcaption');caption.textContent=`${t.name} · ${label}`;f.append(c,caption);return f;}
function custom(){if(atlas.naturalWidth)$('#custom').replaceChildren(...TANKS.map(t=>card(t,'현재 조합',levels)));}
function gallery(){if(!atlas.naturalWidth)return;const mode=$('#compare').value;$('#gallery').replaceChildren(...TANKS.map(t=>{const section=document.createElement('section'),h=document.createElement('h2'),grid=document.createElement('div');h.textContent=t.name;grid.className='grid';for(let lv=0;lv<=5;lv++)grid.append(card(t,lv===0?'기본형':`${mode==='all'?'전체':UPGRADES[mode].label} ${lv}단계`,Object.fromEntries(Object.keys(UPGRADES).map(id=>[id,mode==='all'||mode===id?lv:0]))));section.append(h,grid);return section;}));}
for(const [id,u] of Object.entries(UPGRADES)){const label=document.createElement('label');label.innerHTML=`<span>${u.label} <output>0</output> / 5</span><input aria-label="${u.label}" type="range" min="0" max="5" step="1" value="0">`;label.querySelector('input').oninput=e=>{levels[id]=Number(e.target.value);label.querySelector('output').value=levels[id];custom();};$('#controls').append(label);const option=document.createElement('option');option.value=id;option.textContent=u.label;$('#compare').append(option);}
$('#compare').onchange=gallery;atlas.onload=()=>{custom();gallery();$('#status').textContent='전차 4종 · 개량 6종 · 기본형~5단계 준비 완료';};atlas.onerror=()=>{$('#status').textContent='이미지를 불러오지 못했습니다. 새로고침해 주세요.'};atlas.src='/assets/art/tanks.png';
